language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.2"
  - DJANGO="django>=2.2,<3.0"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.2"
   - python: "2.7"
     env: DJANGO="django>=2.2,<3.0"

branches:
  only:
    - master
    - gsoc2019

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint
  - jslint django_netjsonconfig/static/django-netjsonconfig/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - |
      openwisp-utils-qa-checks \
        --migration-path ./django_netjsonconfig/migrations/ \
        --skip-checkmakemigrations
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
      openwisp-utils-qa-checks \
        --skip-isort \
        --skip-flake8 \
        --skip-checkmigrations \
        --skip-checkendline \
        --skip-checkcommit \
        --migration-module django_netjsonconfig
    fi
  - coverage run --source=django_netjsonconfig runtests.py

after_success:
  coveralls
